### ISSUE TITLE
Support typedBecome with new TotalUnion protocol

### ISSUE THREAD

**Issue by mkotsbak** [knutwalker/typed-actors#4]
If possible, please add typedBecome[NewMessageType]

```
  final def typedBecome[NewMessageType <: Union](f: PartialFunction[NewMessageType])(implicit ev: NewMessageType isPartOf Message): Unit =
    context become untypedFromTyped(f)
```

Often become() means the actor changes state and accepts different messages
ofc that would not be checked by the outside, but a check that the handler can handle all relevant types (used with TotalUnion)
Now I can't use TotalUnion because of that.

**Comment by mkotsbak** [comment]
Maybe typedBecome[] must have a different name.

**Comment by mkotsbak** [comment]
It would make sense to also have a version without Union:

```
  final def typedBecome[NewMessageType](f: PartialFunction[NewMessageType]): Unit =
    context become untypedFromTyped(f)
```

**Comment by knutwalker** [comment]
I'm ok with adding an overload to `typedBecome` for subcases of the union message type, but I don't think I want to add the `typedBecome[NewMessageType]`. If you have to use a completely new type that you couldn't anticipate statically (either by having a union type or an ADT), there is always regular `context.become` and I'm ok with falling back to untyped actors in corner cases.

**Comment by mkotsbak** [comment]
I'm fine with that, but need a subset of more than one of the messages in the protocol.

**Comment by knutwalker** [comment]
This is the use case for `Union`:

``` scala
type Message = A | B | C

typedBecome { Union
  .on[A] { case a => ... }
  .on[B] { case b => ... }
  .apply
}
```

**Comment by mkotsbak** [comment]
Well, sure, But I would like the use case to be:

``` scala
type Message = A | B | C

totalUnionBecome[B | C] {
  .on[A] { case a => ... }
  .on[B] { case b => ... }
  .apply
}
```

:)

**Comment by mkotsbak** [comment]
Is my use case in comment https://github.com/knutwalker/typed-actors/issues/4#issuecomment-154435666 now supported?
